<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'g.tea126@gmail.com',
		'to' => 'g.tea126@gmail.com'
	),
	'fields' => array(
		'Email' => array(
			'order' => 6,
			'type' => 'email',
			'label' => 'Your Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Your Name\' is required.',
				'format' => 'Field \'Your Name\' has an invalid email.'
			)
		),
		'custom_U635' => array(
			'order' => 1,
			'type' => 'checkbox',
			'label' => 'Protect Native Birds',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Protect Native Birds\' is required.'
			)
		),
		'custom_U709' => array(
			'order' => 2,
			'type' => 'checkbox',
			'label' => 'Attaching Bells',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Attaching Bells\' is required.'
			)
		),
		'custom_U725' => array(
			'order' => 3,
			'type' => 'checkbox',
			'label' => 'Keep Indoors',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Keep Indoors\' is required.'
			)
		),
		'custom_U741' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => 'Desexing',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Desexing\' is required.'
			)
		),
		'custom_U757' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Your Pet Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Your Pet Name\' is required.'
			)
		),
		'custom_U5237' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Email Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email Address\' is required.'
			)
		)
	)
);

process_form($form);
?>
